### ISSUE TITLE
Remove language for pulling down ApexDocJS repo from README

### ISSUE THREAD

**Issue by MatthewBlanski** [MatthewBlanski/ApexDocJS#17]
Change the language in README.md to suggest pulling down the latest release instead of the repo. The master branch, while stable, may precede the current release and not contain features in the current release notes.

**Comment by arvind0598** [comment]
That's a bit confusing. The master should always be updated whenever you make a release right?

**Comment by MatthewBlanski** [comment]
> That's a bit confusing. The master should always be updated whenever you make a release right?

The current state for this is following the SFDO flow for github work, meaning that main  can be in a state that is not currently not released.

**Comment by arvind0598** [comment]
Ah you're saying while you have an active release branch going on you'd want users to clone the repository and contribute to the same release branch instead of checking out a new branch from master?

**Comment by MatthewBlanski** [comment]
That is somewhat inverted. We don't want end-users to pull down the code from our main branch to use this. We want them to use the most recent release.

**Comment by arvind0598** [comment]
Shouldn't you be having a branch for the latest release then? Downloading the source code from the releases section and then using git locally and setting everything up again is harder to setup and start contributing, compared to just having to fork the repository and then clone and get started. 

Also good to know because I already started on the other issue with a forked repository on the main branch already, and I'll get rid of that and start over with the latest release instead haha.

**Comment by MatthewBlanski** [comment]
Please contribute and develop off of main.

If you intend to run the application as an end user, please use a release.
